{
"provider": "AWS",
  "propities": {
    "type": "t2.micro",
    "region": "us-east-1",
    "vpc": "vpc-123456",
    "ami": "ami-0abcdef1234567890"
  }
}
{
  "provider": "AZURE",
  "propities": {
    "type": "Standard_B1s",
    "resourceGroup": "rg-prueba",
    "redVital": "vnet-prueba"
  }
}
{
  "provider": "GCP",
  "propities": {
    "type": "n1-standard-1",
    "zone": "us-central1-a",
    "diskBase": "pd-standard",
    "project": "mi-proyecto-gcp"
  }
}
