@startuml cloud-factory

'------------- familias 1 virtualMachine ------------
abstract class VM {
# String Ram
# String CPUs
# String disk

+ getters()
+ setters()
}

class AWSVm {
- AWSMachineType type
- String Region
- String VPC
- String AMI
+ getters()
+ setters()
}
class AzureVm{
- AzureMachineType type
- String  resourceGroup
- String redVital
+ getters()
+ setters()
}
class GCPVm{
- GCPMachineType type
- String zone
- String diskBase
- String project
+ getters()
+ setters()
}
class OnPromiseVm{
    - String networkPhysical
    + getters()
    + setters()
}

enum AWSMachineType{
    t2.micro 
    m5.large
}
enum AzureMachineType {
    Standard_B1s
}
enum GCPMachineType {
    n1-standard-1
}

'------------- Familia 2 Network ---------------

abstract class Network {
    # String networkName
    # String subnetName
    # String securityPolicy
    + getters()
    + setters()
}

class AWSNetwork {
    - String vpcId
    - String subnet
    - String IdsecurityGroup
    + getters()
    + setters()
}

class AzureNetwork {
    - String virtualNetwork
    - String subnetName
    - String networkSecurityGroup
    + getters()
    + setters()
}

class GPCNetwork {
    - String networkName
    - String subnetworkName
    - String firewallTag
    + getters()
    + setters()
}

class OnPromiseNetwork {
    - String physicalInterface
    - String vlanId
    - String firewallPolicy
    + getters()
    + setters()
}
'-----------------------------------------------


'------------- Familia 3 Disk ------------------
abstract class Disk {
    # String scale
    # int sizeGB
    + getters()
    + setters()
}

class AWSDisk {
    - volumeTypeAWS type
    - boolean encrypted
    + getters()
    + setters()
}

class AzureDisk {
    - diskSku type
    - boolean autoDelete
    + getters()
    + setters()
}

class GPCDisk {
    - diskTypeGPC type
    - boolean autoDelete
    + getters()
    + setters()
}

class OnPromiseDisk{
    - String storagePoo
    - String raidLevel
    + getters()
    + setters()
}

enum volumeTypeAWS {
    gp2 
    io1
}

enum diksSku {
    Standard_LRS
    Premium_LRS
}

enum diskTypeGPC {
    pd-standard
    pd-ssd
}

'-----------------------------------------------


'----------------- Fabricas --------------------

abstract class Cloud{
+ {abstract} ProvisionResult VmSupply(VM vm)
+ {abstract} ProvisionResult NetWorkSupply(Network net)
+ {abstract} ProvisionResult DiskSupply(Disk disk)
}

class ProviderCloud {
    - Map<String, Cloud> methods
    + Cloud getProvider()
}

class AWS{}
class AZURE{}
class GCP{}
class OnPromise{}

'-----------------------------------------------

enum statusResult {
    SUCCESS
    ERROR
}

class ProvisionResult {
    - statusResult status
    - VM vm
    - string message
}

' ----------------- Relaciones --------------------

Cloud <|-- AWS
Cloud <|-- GCP
Cloud <|-- AZURE
Cloud <|-- OnPromise

GCP --> GCPVm : create
GCP --> GPCDisk : create
GCP --> GPCNetwork : create

AWS --> AWSVm : create
AWS --> AWSNetwork : create
AWS --> AWSDisk : create

AZURE --> AzureNetwork : create
AZURE --> AzureVm : create
AZURE --> AzureDisk : create

OnPromise --> OnPromiseVm : create 
OnPromise --> OnPromiseDisk : create
OnPromise --> OnPromiseNetwork : create

Cloud --> ProviderCloud

VM <|-- AzureVm
VM <|-- GCPVm
VM <|-- AWSVm
VM <|-- OnPromiseVm

Network <|-- AzureNetwork
Network <|-- AWSNetwork
Network <|-- GPCNetwork
Network <|-- OnPromiseNetwork

Disk <|-- AWSDisk
Disk <|-- OnPromiseDisk
Disk <|-- AzureDisk
Disk <|-- GPCDisk

AzureMachineType <-- AzureVm : has
AWSMachineType <-- AWSVm : has
GCPMachineType <-- GCPVm : has 

AWSDisk --> volumeTypeAWS : has
AzureDisk --> diksSku : has
GPCDisk --> diskTypeGPC : has


Cloud --> ProvisionResult: return
statusResult <-- ProvisionResult : has


@enduml